Gemfile
Gemfile.lock

Adds 2 gems, mainly for seed file.
Please review

adds faker and colorize gem

---

Gemfile
Gemfile.lock
db/migrate/20220518001826_create_active_storage_tables.active_storage.rb
db/schema.rb

Installed active storage to be able to manipulate the DB in the seed file.

Install active storage

---

app/models/allergen.rb
app/models/diet.rb
app/models/item.rb
app/models/transaction.rb

@DenzelBraithwaite Added validations to 4 models. Thanks!

added validations in all created models

---

app/controllers/chatrooms_controller.rb
app/controllers/messages_controller.rb
app/controllers/users_controller.rb
test/controllers/chatrooms_controller_test.rb
test/controllers/messages_controller_test.rb
test/controllers/users_controller_test.rb

@DenzelBraithwaite Please review the three controllers created so we may start working on user stories individually! :)

created controllers for chatrooms, messages, users

---

app/controllers/profiles_controller.rb
app/controllers/users_controller.rb
app/models/item.rb
config/routes.rb

Added all routes described on our google sheet. Please take the time to review each controllers routes, using `rails routes | grep CONTROLER_NAME` for a more condensed view of the routes.
@stshayna

Adding routes

---

app/controllers/items_controller.rb
app/models/item.rb
app/views/items/_form.html.erb
app/views/items/index.html.erb
app/views/items/new.html.erb
app/views/items/show.html.erb
db/migrate/20220520010004_add_name_to_items.rb
db/migrate/20220520191857_update_items_table.rb
db/schema.rb
test/models/item_test.rb

@DenzelBraithwaite Created basic view pages for items:
- index
- show
- new/create
- _form.html.erb (for creating a new item)
Added "name" as a new field in Items table too.

Basic views

---

app/controllers/feedbacks_controller.rb
app/controllers/transactions_controller.rb
test/controllers/feedbacks_controller_test.rb
test/controllers/transactions_controller_test.rb

@DenzelBraithwaite All controllers are now generated! Thanks.

created plain Feedbacks and Transactions controllers

---

app/assets/stylesheets/components/_message.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

1. Created basic navbar with 4 icons and a dropdown menu for login/log out.
Details, e.g. icons/links, can change after any further discussion!
2. Updated colors of messages in chatroom to align with Figma.

navbar with icons

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/models/item.rb
app/views/layouts/application.html.erb
config/cable.yml
db/schema.rb
test/models/item_test.rb

Here's how it looks like.
We can still change the padding later o
n

adding the background layout we will use throughout the app

---

app/models/allergen.rb
app/models/diet.rb
app/models/feedback.rb
app/models/item.rb
app/models/items_allergen.rb
app/models/items_diet.rb
app/models/request.rb
app/models/user.rb
db/schema.rb
db/seeds.rb
test/models/item_test.rb

Most models were affected by this, I **Highly** recommend reviewing this with the Kitt DB schema open. Along with the changes, I also added some comments for clarity. I changed the following model associations:
1. where `has_and_belongs_to_many` was used, it's been replaced with `has_many` and `has_many, through:`
2
_(P.S. At the time of making this PR, I noticed a few small typos that were commented out in a few model files. I will make another quick push after this to fix these.)_
Please review these changes when you get a moment :) @stshayna

Fix model associations

---

app/models/feedback.rb
app/models/user.rb
db/migrate/20220528185754_remove_request_from_feedbacks.rb
db/schema.rb
test/models/feedback_test.rb

Removed requests from feedbacks. Not a big change here. You can test this out by looking at your schema after a rails db:migrate or by running rails c and testing the models. THanks

Remove request from feedback

---

app/views/layouts/application.html.erb

fixed small bug

---

app/models/item.rb

simple fix for adding back enums to item.status
it works with pg search as well (tested).

fixed item.status and added back enums

---

app/views/items/index.html.erb

@DenzelBraithwaite  it's working now ! You can click on the image of the card too

the whole card is clickable

---

app/assets/stylesheets/components/_button.scss
app/controllers/requests_controller.rb
app/models/item.rb
app/views/items/show.html.erb
app/views/requests/index.html.erb
db/seeds.rb
test/models/item_test.rb

@DenzelBraithwaite Please review the changes:
1. Added logic in items#show page that owners cannot book his/her own items.
2. Added logic in requests#index page that the page doesn't crash if a request doesn't have any messages (the request won't show in the page).
3. Added space between fake first names and last names in seeds.

owners cannot book his own items

---

app/assets/stylesheets/components/_button.scss
app/assets/stylesheets/components/_message.scss
app/controllers/requests_controller.rb
app/models/item.rb
app/views/items/show.html.erb
app/views/layouts/application.html.erb
app/views/requests/index.html.erb
db/seeds.rb
package.json
test/models/item_test.rb
yarn.lock

@DenzelBraithwaite Please review the changes:
1. Added in fade in effect to new messages in Requests#show page

(Please review the earlier PR first) Popup messages

---

app/assets/meal_descriptions.json
app/controllers/items_controller.rb
app/views/items/show.html.erb
db/seeds.rb

Changes for pitch, I will leave comments in the files to explain.

Create pitch update seed maybe

---

app/views/items/show.html.erb

@stshayna @DenzelBraithwaite 
map changed to Montreal and removed second and third slide for the carousel

cloudinary is working

---

app/models/message.rb
app/views/items/index.html.erb
db/schema.rb
test/models/message_test.rb

@MarlAndre @stshayna @DenzelBraithwaite pls review and merge. the map was uncomment

removed map

---

Gemfile
Gemfile.lock
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

1. Removed dropdown menu in the navbar because the phone screen is too small to have that.
2. Added optional active class to navbar icons such that the background will change to white for the active class.
Anyone who has the time, please help review it :)

Active navbar

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_container.scss
app/controllers/items_controller.rb
app/models/message.rb
app/views/items/index.html.erb
app/views/items/my_items.html.erb
app/views/items/show.html.erb
db/schema.rb
test/models/message_test.rb

@DenzelBraithwaite @MarlAndre @stshayna 
1- the carousel is working.
2- the picture linked to the item is working.
3- the avatar picture for Justin appears in the show.
4- allergens and dietary a
ppears in the show.

Show page avatar and item photo

---

app/views/requests/index.html.erb

To anyone who has time, please review the refactored codes on the messages previews.
The page looks exactly the same and just the codes are refactored using `truncate` method. ^0^

simplified codes

---

app/controllers/items_controller.rb
app/views/items/show.html.erb

I added the map on the show page, however, it shows all the item around instead of just the one we clicked on.
Will open a ticket on Tuesday unless someone wants to have a look at it.

Map show page

---

app/assets/stylesheets/components/_cards.scss
app/controllers/items_controller.rb
app/views/items/my_items.html.erb

@MarlAndre @stshayna @DenzelBraithwaite 
Please review this PR for the tabs. Just missing to center it and change the color of the hyperlink. To be done on Thursday.

tabs are done, just need to be centered and change the color for the hyperlink

---

app/assets/stylesheets/components/_profile.scss
app/views/profiles/my_profile.html.erb

Created link to "Log out" in My Profile page.

logout link in my profile page

---

app/views/items/show.html.erb
app/views/pages/my_favorites.html.erb
app/views/shared/_navbar.html.erb

@MarlAndre I've updated the icon and link to My Favorites in the navbar. There're different heart icons as attached, if you'd prefer a different one, let me know and I need to change the same icon in the show page too.

changed icon

---

app/views/items/index.html.erb

removed the container from index apge

removed postal container from index

---

app/controllers/requests_controller.rb
app/views/requests/show.html.erb

Adds distance logic to chat (request controller and show)

adds distance to chat

---

app/assets/stylesheets/components/_container.scss
app/assets/stylesheets/components/_homepage.scss
app/controllers/items_controller.rb
app/javascript/controllers/postal_code_controller.js
app/views/items/index.html.erb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
config/routes.rb

A lot of changes here, the reason is that if we enter the postal code in the landing page, it will changes the address of the user everytime they enter a different address.
To avoid that behaviour, we have to put the landing page in the index page (the index page is now our root path & the landing page design is a popup) so when we enter an address, the landing disappear and shows the result.
There's still an issue in the controller to fix because the real results are not filtering

changed behaviours of the landing screen, it is now a popup

---

app/views/layouts/application.html.erb

fixed issue

---

app/models/item.rb

Very small fix, see files changed.

small fix, adds photos validation and fixes item_status conflict

---

app/assets/stylesheets/components/_navbar.scss

remove border-radius in navbar

---

app/models/item.rb
db/seeds.rb

Fixed an issue where seed file was crashing. 
1. saved the item only after the photo was attached.
2. decreased description minimum length to 7 (there's a very small chance the description is only 7 chars, which breaks)

fixed issues where seed file would crash

---

app/assets/stylesheets/components/_form.scss
app/views/items/_form.html.erb

changes in the new item form:
- reduce margin-top after adding the 'Back' button
- `description` is minimum 7 characters now based on the model validation
- changed wording of the submit button to "create an offer" re: front-end feedback

New item form

---

app/controllers/items_controller.rb
app/controllers/profiles_controller.rb
app/controllers/requests_controller.rb
app/models/item.rb
app/views/layouts/application.html.erb
app/views/profiles/my_profile.html.erb

Changed my profile page
Removed extra buttons, left 'My items' and centered it. Below that I listed items where the user has made a request.
As always, I will leave comments on the files changed so please review them.
Thank you

Change my profile

---

app/assets/stylesheets/components/_homepage.scss
app/views/items/index.html.erb

my changes has not been saved, here is the landing page

---

app/views/items/_form.html.erb

changed wording of the button in new item form as discussed

---

app/controllers/pages_controller.rb
app/views/pages/my_favorites.html.erb
db/schema.rb

Added distance logic to favorites page. VERY similar to other pages that calculate distance, but for now it's calculating ALL users distance in the back-end but load times are still fast. Still, in the future I'd like to change this but I'm not sure how to only calculate those who have favorites.

Add distance to favorites

---

app/models/item.rb
app/views/items/_form.html.erb

added new item form validations

---

app/views/items/show.html.erb

Hello, just a suggestion to change "expiration date on" to "best before" in show card (more padding on the right in that case too).
Before:
After:

suggested wording change

---

app/views/items/index.html.erb
app/views/profiles/my_profile.html.erb

Just like the card styling in the index page! ;)

changed item card styling for the distance and address

---

app/assets/stylesheets/components/_button.scss
app/views/items/show.html.erb

back button in show page with less margin

---

db/seeds.rb

added seed ingredient 'sugar', owned by J-F

---

app/controllers/items_controller.rb
app/controllers/pages_controller.rb

It's not breaking anymore on any pages. Please merge me !

Fixed breaking issue

---

app/assets/ingredients.json

Moving `sugar` to the last of the list of ingredients for `@jf` to own it in the seeds.

moving cup of sugar to the last in the ingredients list

---

app/assets/stylesheets/components/_request.scss
app/views/layouts/application.html.erb
app/views/requests/index.html.erb

Message window is fixed and not "scrollable" now :)

fixed vh for requests#show page

---

config/environments/production.rb

Will help to setup an SSL certificate to secure the app. It will use https instead of http

will help secrure the app

---

app/assets/close_locations.json
app/assets/ingredients.json
app/controllers/items_controller.rb
app/controllers/pages_controller.rb
app/controllers/profiles_controller.rb
db/seeds.rb

Worked on the seed to get it ready for the pitch / demo. Here's a highlight of my many but small changes:
- Changed cucumber description to better reflect the image (one cucumber, not multiple)
- Changed "sugar" to "cup of sugar" and modified the description
- Used "Montreal, Av. Casgrain" as our address across all files, it's only a 0.2km difference than before.
- Small visual redesign of seed, the word "created" is now also in green.
- ![image](https://user-images.githubusercontent.com/85902450/174154201-d00bff4a-38b6-4902-aa6d-1c717b7c3bdc.png)
- Added past message, requesting celery but it has already been donated by now
- Changed addresses to be more generic (not specific "1234 street name", instead just "street name")
Please review and merge these changes, let me know if anything …

Change seed

---

app/views/items/_form.html.erb
app/views/items/index.html.erb

For the Postal code Form and Add a new item for, I disabled the submit button once they're click.
The text of the button is also changing so the user can see it's sending data.

once we clicked a submit button, the user cant click it again

---

app/views/items/_info_window.html.erb

A simple change to make the username bold as a front-end tweak.

make the username bold in the map marks

---

app/assets/stylesheets/components/_cards.scss

changed opacity of the icon

---

app/assets/stylesheets/components/_profile.scss
app/views/profiles/my_profile.html.erb

I applied the styling suggested by Stephane during rehearsal.
There's less padding between the items

changed styling of profile page so we can have less blank space
