app/models/transaction.rb

@DenzelBraithwaite When the name of the relation doesn’t match the name of the model:
class Transaction < ApplicationRecord
belongs_to :giver, class_name: "User"
belongs_to :receiver, class_name: "User"
Added `class_name: "User"` to link to giver and receiver.

adding 'User' as class_name to giver and receiver

---

app/assets/stylesheets/components/_message.scss
app/controllers/application_controller.rb
app/models/user.rb
app/views/messages/_message.html.erb
app/views/requests/index.html.erb
app/views/requests/show.html.erb
db/migrate/20220531184620_add_time_zone_to_user.rb
db/schema.rb
test/models/user_test.rb
yarn.lock

@DenzelBraithwaite Please review changes:
1. Requests#show page
- Message received time is using Rails' default timezone (UTC). To update that, I've added `time_zone` column to the `Users` table and set it to EST be default. In that case, all users can update their timezones further in their edit_profile page (this page to be created next week).
2. Requests#index page
- Added logics in so it won’t crash when there’s no requests || no messages for a request.

Timezone reset

---

app/models/message.rb
db/schema.rb
test/models/message_test.rb

Realised It was accidentally removed in the master, hence adding back `:request_id` as `not null` in the `Message` model.
For anyone who has time, please review this PR :)

Message model - request_id

---

app/models/item.rb
db/migrate/20220604160852_remove_coordinates_from_items.rb
db/schema.rb
test/models/item_test.rb

Removes coordinates from the Item model. You can `rails db:migrate` and check your schema to confirm.

removed lat and lon from items. User will use User.address for Geocoder

---

app/controllers/items_controller.rb
app/controllers/pages_controller.rb

Because we look for the `current_user.id` on the show page, but also allow a user to not be signed in, it crashes on the show page. This prevents a user from viewing the show page before they sign in.

prevent app from crashing on show page

---

app/views/requests/index.html.erb

@everyone, this is a very simple re-coding: with enums, `item.status=='donated'` can be written as `item.donated?` instead.
Please review when you have time :)

item.donated?

---

app/controllers/items_controller.rb
app/javascript/controllers/postal_code_controller.js
app/models/message.rb
db/schema.rb
test/models/message_test.rb

Fix issue where @users or @items was being reassigned accidentally in the items controller #index method.
This fix is hard to see at the moment, due to the DOM not accurately showing our code, but if you use a raise, then open the console and inspect the error, it will bring you to the raise page. From there, you can use `@users.size` or `@users.length `to see if it's really filtering the number of items being displayed, after entering a postal code.
Please take your time to review this, thank you.

Fix filtering in index

---

app/assets/stylesheets/components/_card.scss

@MarlAndre @DenzelBraithwaite @stshayna 
Changed from object-fit contain to cover. It's true that the picture expands to cover the full width of the box, but using other values strech or shrink the pictures

changed object-fit from contain to cover

---

app/models/item.rb

added `:item_type` into pg_search filter so we can search "meal" / "ingredient".

add item_type into search filter

---

app/assets/stylesheets/components/_card.scss
app/views/items/index.html.erb
app/views/pages/my_favorites.html.erb
app/views/profiles/my_profile.html.erb
app/views/requests/index.html.erb

Changes in this PR:
when an item is `reserved` / `donated`, its index card and message cards will all change to gray color. `item.description` in those cards will be replaced by `This item was donated.` / `This item is reserved.`
Used one shade of gray color only, otherwise the page has too many colors i think.

Card colors status

---

app/assets/stylesheets/components/_like_button.scss
app/assets/stylesheets/config/_colors.scss
app/javascript/controllers/toggle_favorite_controller.js
app/views/items/show.html.erb

The error was probably caused by the class `favorite_border` added by another branch, the class is removed given the relevant js codes were commented out and not in use. 
Also changed the color of the favorite icon to our theme color as suggested in feedback session.

fixed toggle effect of fav icon

---

app/views/items/index.html.erb
app/views/pages/my_favorites.html.erb
app/views/profiles/my_profile.html.erb

There's a previous branch that shorten the item description in index cards, so making the same change for the item cards in other pages as well and the cards will have better padding.

make item description shorter in cards

---

app/views/items/show.html.erb
app/views/requests/show.html.erb

Updated avatar images in item cards with three scenarios:
1. Demo user 'Justin' will use Denzel's img.
2. Giver 'Shayna' will use Shayna's img.
3. Everyone else will use the landing page img.

udpated user images in cards

---

app/assets/stylesheets/components/_cards.scss
app/views/items/show.html.erb

Hello,
Margin is added at the bottom of both index and show pages so we can easily locate the last item (in index page) and the reserve button (in show page).
Index page (before and after):
Show page button:

index and show pages

---

app/assets/stylesheets/components/_card.scss
app/views/items/index.html.erb
app/views/items/my_items.html.erb
app/views/pages/my_favorites.html.erb
app/views/profiles/my_profile.html.erb

Figured out a way to fix the images without stretching them (wrapped in a div) :)
Before:
After (all good!):

wrapped img by a div

---

app/assets/stylesheets/components/_card.scss
app/views/items/index.html.erb
app/views/pages/my_favorites.html.erb

I changed the styling of the cards in the index.
Address and distance are on the same line, and distance is bold to make it pop more.
I used truncate on the address otherwise it was displaying everything on a second line and was messing with the desired styling.

Card index

---

app/assets/stylesheets/components/_profile.scss
app/views/profiles/my_profile.html.erb

As discussed, logout link in My Profile page is visible now. And also changed `requested items` with uppercase.

logout button

---

app/assets/stylesheets/components/_card.scss
app/views/items/index.html.erb
app/views/pages/my_favorites.html.erb
app/views/profiles/my_profile.html.erb
app/views/requests/index.html.erb
db/seeds.rb

Few changes here:
1. For items that are reserved or donated, their cards will be in different colors, i.e. gray and dark-gray.
2. Fixed to have the same styling for distance and address on the same line in the item cards for all pages.
3. In seeds, Justin the demo user has favorited the 'sugar' ingredient.

reserved and donate item cards have different colors

---

app/controllers/items_controller.rb
app/views/items/index.html.erb
app/views/items/show.html.erb
app/views/pages/my_favorites.html.erb
app/views/profiles/my_profile.html.erb

Please review some changes here:
1. Index page
- filter the `@items` in `items` controller so only available/reserved items will appear
- shorten address by 2 chars so it can be shown in one line
- add the same space between distance and address (did the same for item cards in my favs and my profile pages too)
Result (donated items not shown):
2. Show page
- tidy up the div indentations
- group allergens/diets in one line

Index no donated

---

app/controllers/pages_controller.rb
app/controllers/requests_controller.rb

When we add something to favorite or we send a messages to request an item, it goes on top.
Here's a visual with favorites page :

last item added to favorite or messages sent will be on top

---

app/controllers/profiles_controller.rb

As discussed during rehearsal, the requested items in My Profile page are re-ordered by `item.id`.

re-order the items for 'requested items'
